server:
  port: 8090
spring:
   application:
      name: auth
   datasource:
      driver-class-name: org.postgresql.Driver
      username: root
      password: root
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth
   jpa:
      properties:
         hibernate:
            default_schema: auth
            dialect: org.hibernate.dialect.PostgreSQLDialect
            hbm2ddl:
              auto: none
            proc.param_null_passing: true
            jdbc:
                time_zone: UTC-3
            show-sql: true
   mail:
     username: @gmail.com
     password: zwouaxujgztkeupl
     port: 587
     host: smtp.gmail.com
     properties:
       mail:
         smtp:
           starttls:
             enable: true
           auth: true
#   sql:
#     init:
#       mode: always
#       schema-locations: classpath:schema.sql
jwt:
  secret: Efh6U/bVA6sP7srDAEgMvTCXRsovVv2nTokqQ3syM/p/WuFmQcYKa9UvAOHdYClaSlWSTPT0RRcK2h3NK+BrEw==
  expiration: 86400000 #24 horas: